[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/sendTelegram"
  to = "/.netlify/functions/sendTelegram"
  status = 200

[context.production.environment]
  TELEGRAM_BOT_TOKEN = "7885175271:AAEXwydCMX6E78Dvt2uXPR9qn64w1VCe2tM"
  TELEGRAM_CHAT_ID = "6967298820"