[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/sendTelegram"
  to = "/.netlify/functions/notify-order"
  status = 200

[[redirects]]
  from = "/api/notify-order"
  to = "/.netlify/functions/notify-order"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200