[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
  included_files = [".env"]

[build.environment]
  TELEGRAM_BOT_TOKEN = "7765791698:AAEdPdmRYZ3aHiwD0e8hUDmX72grWM1zTNA"
  TELEGRAM_CHAT_ID = "1157438477"
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5174
  port = 8888
  publish = "dist"